messages:
  # 접두사
  prefix: '&9[아이템명령어] &r'

  # 아이템 명령어를 생성하였을 때 출력되는 메세지
  createItemCommand: "{command}&f를 손에 든 아이템에 등록하였습니다."

  # 콘피그를 다시 불러올 때 출력되는 메세지
  reloadConfig: "&a콘피그를 리로드하였습니다!"

errorMessages:

  # 명령어를 실행할 때 권한이 없을 경우 출력되는 메세지
  noPermission: "&c당신은 해당 명령어를 사용할 권한이 없습니다."

  # 콘솔에서 명령어를 사용할 경우 출력되는 메세지
  noConsole: "&c해당 명령어를 콘솔에서 사용할 수 없습니다."

  # 아이템 명령어를 생성할 때 명령어를 입력하지 않았을 경우 출력되는 메세지
  noCommandName: "&c생성할 명령어를 슬래시를 제외하고 입력해주세요."

  # 아이템을 손에 들지 않고 아이템 명령어를 생성하려고 했을 때 출력되는 메세지
  noItemInHand: "&c손에 아이템을 들고 사용해주세요."
